cocos/example-projects

assets/cases/01_graphics/01_sprite/atlas_sprite.fire
assets/cases/01_graphics/01_sprite/simple_sprite.fire
assets/cases/01_graphics/01_sprite/sliced_sprite.fire
assets/cases/02_ui/01_widget/auto_resize.fire
assets/cases/02_ui/01_widget/widget_align.fire
assets/cases/02_ui/03_button/simple_button.fire
assets/cases/02_ui/04_progressbar/progressbar.fire
assets/cases/02_ui/05_scrollView/ScrollView.fire
assets/cases/03_gameplay/01_player_control/keyboard_input.fire
assets/cases/03_gameplay/01_player_control/touch_input.fire
assets/cases/03_gameplay/02_actions/simple_action.fire
assets/cases/03_gameplay/03_animation/move_animation.fire
assets/cases/03_gameplay/03_animation/sprite_animation.fire
assets/cases/05_scripting/01_properties/ReferenceTypeProperties.js
assets/cases/05_scripting/01_properties/node_array.fire
assets/cases/05_scripting/01_properties/reference_type.fire
assets/cases/05_scripting/02_prefab/MonsterPrefab.js
assets/cases/05_scripting/02_prefab/MonsterPrefab.prefab

 fix _sprite renname _spriteFrame

---

assets/cases/01_graphics/02_particle/ParticleControl1.js
assets/cases/02_ui/03_button/ButtonControl1.js

fix renname

---

assets/cases/02_ui/04_progressbar/ProgressBar.js
assets/cases/02_ui/04_progressbar/ProgressBar.js.meta
assets/cases/02_ui/04_progressbar/progressbar.fire

fixed https://github.com/fireball-x/fireball/issues/1375

improve progressBar demo

---

assets/cases/02_ui/03_button/ButtonControl1.js

fix https://github.com/cocos-creator/fireball/issues/1538

fix button display string

---

assets/cases/01_graphics/01_sprite/SlicedSprite.fire
assets/cases/02_ui/03_button/ButtonInScroll.fire
assets/cases/02_ui/03_button/SimpleButton.fire
assets/cases/02_ui/04_progressbar/progressbar.fire
assets/cases/02_ui/06_layout/LayoutNone.fire
assets/cases/02_ui/07_editBox/EditBox.fire
assets/res/textures/default_scrollbar_bg.png.meta

fix button click event name.

---

assets/cases/05_scripting/03_events/MouseEvent.js

Test case for https://github.com/cocos-creator/fireball/issues/2162

Add mouse move test

---

assets/TestList.fire
assets/res/imported/spine/spineboy.json.meta

fixed readme background display error.

---

assets/cases/02_ui/07_editBox/EditBox.fire

change maxLength from -1 to 10000

---

assets/cases/05_scripting/08_module/LoadModuleCtrl.js
assets/cases/05_scripting/08_module/load_module.fire

https://github.com/cocos-creator/fireball/issues/2319 
3.Load_module:界面显示异常

fix Load_module: Interface display abnormal

---

assets/cases/05_scripting/10_loadingBar/LoadingBarCtrl.js
assets/cases/05_scripting/10_loadingBar/loadingBar.fire
assets/scripts/Global/SceneList.js

https://github.com/cocos-creator/fireball/issues/2389 
LoadingBar的第二次无法加载 error

fix  LoadingBar Exmaple

---

assets/cases/05_scripting/07_asset_loading/AssetLoading.js

https://github.com/cocos-creator/fireball/issues/2389

fix asset_loading下的audio播放失败

---

assets/cases/05_scripting/08_module/load_module.fire

https://github.com/cocos-creator/fireball/issues/2319

fix 关闭说明页面在android版本上还是显示异常

---

assets/cases/05_scripting/07_asset_loading/AssetLoading.js

For https://github.com/cocos-creator/fireball/issues/2317

Fix audio in AssetLoading

---

assets/cases/05_scripting/07_asset_loading/AssetLoading.js
assets/res/imported/spine/spineboy.json.meta

Re: https://github.com/cocos-creator/fireball/issues/2278

update asset loading

---

assets/cases/spine/SpineCtrl.js

https://github.com/cocos-creator/fireball/issues/2941

fix example case spine

---

assets/cases/03_gameplay/03_animation/AnimationEvent.fire

https://github.com/cocos-creator/fireball/issues/2544#event-658065635

fix particle texture display error。

---

assets/cases/05_scripting/07_asset_loading/loadResAll_example.js
assets/cases/spine/SpineCtrl.js

https://github.com/cocos-creator/fireball/issues/2984

fix loadReAll example

---

assets/scripts/Global/Menu.js

https://github.com/cocos-creator/fireball/issues/3001

Description Interface example project can not be closed

---

assets/cases/05_scripting/11_network/NetworkCtrl.js
assets/cases/05_scripting/11_network/socket-io.js
assets/cases/05_scripting/11_network/socket-io.js.meta

https://github.com/cocos-creator/fireball/issues/2705

fix network web mobile and desktop bug

---

assets/cases/01_graphics/01_sprite/FilledSprite.fire

https://github.com/cocos-creator/fireball/issues/3128

fix FilledSprite example

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

https://github.com/cocos-creator/fireball/issues/2705

fix network error #fireball/issues/2705

---

assets/cases/05_scripting/07_asset_loading/LoadRes_example.js

https://github.com/cocos-creator/fireball/issues/3158#issuecomment-221820125

fix load SpriteFrame erro for LoadRes_example

---

assets/cases/native_call/Native_Call/NativeCallCtrl.js

https://github.com/cocos-creator/fireball/issues/3359

fix NativeCall error fireball/issues/3359

---

assets/cases/collider/Category/ColliderListener.js

https://github.com/cocos-creator/fireball/issues/3336

remove setDisplayStats in collider example

---

assets/TestList.fire
assets/scripts/Global/Menu.js

https://github.com/cocos-creator/fireball/issues/3332

fix fireball/issues/#3332

---

assets/cases/collider/platform.fire

https://github.com/cocos-creator/fireball/issues/3409

fix follow example for platform

---

assets/cases/native_call/Native_Call.fire
assets/cases/native_call/Native_Call/NativeCallCtrl.js

https://github.com/cocos-creator/fireball/issues/3460
https://github.com/cocos-creator/fireball/issues/3359
修复 Native_Call 提示只有在 android 的移动平台才有效的提示信息

fix Native_Call error for fireball/issues/3460/3359

---

assets/cases/motionStreak/MotionStreak.fire

https://github.com/cocos-creator/fireball/issues/3360

fix button cannot be clicked for MotionStreak example

---

assets/cases/05_scripting/07_asset_loading/LoadResAll.fire
assets/cases/05_scripting/07_asset_loading/LoadResAll/loadResAll_example.js

https://github.com/cocos-creator/fireball/issues/3488

fix LoadResAll error

---

assets/cases/05_scripting/03_events/MouseEvent.js

https://github.com/cocos-creator/fireball/issues/3343

fix MouseEvent bug for #fireball/issues/3343

---

assets/cases/collider/Shooter.fire
assets/cases/collider/Shooter/Shooter.js

https://github.com/cocos-creator/fireball/issues/3332

fix View the description interface exception for #fireball/issues/3332

---

assets/cases/02_ui/01_widget/AlignOnceWidget.fire
assets/cases/05_scripting/07_asset_loading/LoadRes.fire

https://github.com/cocos-creator/fireball/issues/3594

Adjust the font size font fix blur effect for #fireball/issues/3594

---

assets/scripts/Global/Menu.js

for https://github.com/cocos-creator/engine/pull/917
persist node 对外部节点的引用应该在场景每次切换回去之后更新

Menu should retrieve the current sceneList once main scene launched

---

assets/scripts/Global/Helpers.js

fix https://github.com/cocos-creator/fireball/issues/3578
修复 runtime 切换场景时会闪一下

try to fix runtime glitter

---

assets/cases/03_gameplay/03_animation/AnimationCallback.fire
assets/cases/03_gameplay/03_animation/AnimationCallback.fire.meta
assets/cases/03_gameplay/03_animation/AnimationCallback.js
assets/cases/03_gameplay/03_animation/AnimationCallback.js.meta

update https://github.com/cocos-creator/fireball/issues/2614

add animation callback example

---

assets/cases/05_scripting/07_asset_loading/LoadResAll/loadResAll_example.js
settings/project.json

fix loadResAll example in JSB

---

assets/cases/graphics/demo/bacteria.js

https://github.com/cocos-creator/fireball/issues/3743

add runtime protection

---

assets/cases/tiledmap/Puzzle.js

Related issue : cocos-creator/fireball/issues/3717

Solve the error effect in Puzzle example on mobile devices.

---

assets/cases/native_call/Native_Call/NativeCallCtrl.js

https://github.com/cocos-creator/fireball/issues/3843

add native call for runtime tip for fireball/issues/3843

---

assets/cases/collider/platform.fire

https://github.com/cocos-creator/fireball/issues/3857#issuecomment-236836954
初始节点位置往左移动一点。。

refine platform example

---

assets/TestList.fire
assets/cases/02_ui/06_layout/Layout_None/Layout_None_Grid.fire
assets/cases/02_ui/06_layout/Layout_None/Layout_None_Horizontal_Vertical.fire
assets/cases/02_ui/06_layout/Layout_ResizeChildren/Layout_ResizeChildren_Grid.fire
assets/cases/02_ui/06_layout/Layout_ResizeChildren/Layout_ResizeChildren_Normal.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Basic.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Grid.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Normal.fire

fix description interface exception for fireball/issues/3856

---

assets/TestList.fire
assets/scripts/Global/SceneList.js

https://github.com/cocos-creator/fireball/issues/3714

fix fireball/issues/3714

---

assets/cases/graphics/example/arc.js

Re : https://github.com/cocos-creator/fireball/issues/3986

fixed graphics arc

---

assets/TestList.fire
assets/cases/02_ui/06_layout/Layout_None/Layout_None_Grid.fire
assets/cases/02_ui/06_layout/Layout_None/Layout_None_Horizontal_Vertical.fire
assets/cases/02_ui/06_layout/Layout_ResizeChildren/Layout_ResizeChildren_Grid.fire
assets/cases/02_ui/06_layout/Layout_ResizeChildren/Layout_ResizeChildren_Normal.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Basic.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Grid.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Normal.fire
assets/cases/native_call/Native_Call/NativeCallCtrl.js
assets/scripts/Global/SceneList.js

由于这几个 issue 是 1.2 的，但是提交到了 master 分支所以需要重新提交到 1.2 分支才可验证是否已经修复

fix fireball/issues/3714 fireball/issues/3856 fireball/issues/3843

---

assets/cases/05_scripting/07_asset_loading/LoadResAll.fire

https://github.com/cocos-creator/fireball/issues/4025

update LoadResAll title position for fireball/issues/4025

---

assets/cases/01_graphics/02_particle/ToggleParticle.fire
assets/cases/01_graphics/02_particle/ToggleParticle.fire.meta
assets/cases/01_graphics/02_particle/ToggleParticle/ParticleControl.js
assets/i18n/data/en.js
assets/i18n/data/zh.js

https://github.com/cocos-creator/fireball/issues/4049

fix ToggleParticle bug for fireball/issues/4049

---

assets/cases/graphics/RuntimeLabel.prefab
assets/cases/graphics/example/arc.fire
assets/cases/graphics/example/ellipse.fire
assets/cases/graphics/example/lineTo.fire
assets/cases/graphics/example/linejoin.fire
assets/cases/graphics/example/rect.fire

update https://github.com/cocos-creator/fireball/issues/3842

change graphics info to black

---

assets/TestList.fire.meta
assets/cases/02_ui/05_scrollView/ListView.fire.meta
assets/cases/02_ui/05_scrollView/PageView.fire
assets/cases/02_ui/05_scrollView/PageView.fire.meta
assets/cases/02_ui/05_scrollView/PageView.meta
assets/cases/02_ui/05_scrollView/PageView/PageViewCtrl.js
assets/cases/02_ui/05_scrollView/PageView/PageViewCtrl.js.meta
assets/cases/02_ui/11_richtext/RichText.fire.meta
assets/cases/05_scripting/03_events/EventInMask.fire.meta
assets/cases/05_scripting/07_asset_loading/LoadResAll.fire.meta
assets/cases/collider/Shooter.fire.meta
assets/cases/collider/platform.fire.meta
assets/res/prefabs/Page.prefab
assets/res/prefabs/Page.prefab.meta
settings/builder.json

https://github.com/cocos-creator/fireball/issues/1461

add PageView cases

---

assets/cases/02_ui/05_scrollView/PageView.fire
assets/cases/02_ui/05_scrollView/PageView/PageViewCtrl.js

https://github.com/cocos-creator/fireball/issues/1461

update PageView case

---

assets/cases/tiledmap/Puzzle.fire
assets/cases/tiledmap/Puzzle.fire.meta
assets/cases/tiledmap/Puzzle.js
assets/res/imported/map.tmx

Related issue : cocos-creator/fireball/issues/3120

Update the test case of TiledMap.

---

assets/cases/02_ui/05_scrollView/ListView.fire
assets/cases/02_ui/05_scrollView/ListView.fire.meta

https://github.com/cocos-creator/fireball/issues/4206

fix ListView bug for fireball/issues/4206

---

assets/cases/02_ui/12_slider.meta
assets/cases/02_ui/12_slider/Slider.fire
assets/cases/02_ui/12_slider/Slider.fire.meta
assets/cases/02_ui/12_slider/Slider.meta
assets/cases/02_ui/12_slider/Slider/SliderCtrl.js
assets/cases/02_ui/12_slider/Slider/SliderCtrl.js.meta

https://github.com/cocos-creator/fireball/issues/1462

add slider component cases

---

assets/cases/01_graphics/01_sprite/AtlasSprite.fire
assets/cases/01_graphics/01_sprite/AtlasSprite.fire.meta
assets/cases/01_graphics/01_sprite/FilledSprite.fire.meta
assets/cases/01_graphics/01_sprite/SimpleSprite.fire.meta
assets/cases/02_ui/02_label/BitmapFontLabel.fire.meta
assets/cases/02_ui/02_label/SystemFontLabel.fire.meta
assets/cases/02_ui/03_button/SimpleButton.fire.meta
assets/cases/02_ui/05_scrollView/ScrollView.fire.meta
assets/cases/02_ui/13_checkbox.meta
assets/cases/02_ui/13_checkbox/checkbox.fire
assets/cases/02_ui/13_checkbox/checkbox.fire.meta
assets/cases/02_ui/13_checkbox/checkbox.js
assets/cases/02_ui/13_checkbox/checkbox.js.meta

https://github.com/cocos-creator/fireball/issues/1463

add checkBox examples

---

assets/cases/02_ui/05_scrollView/PageView.fire

https://github.com/cocos-creator/fireball/issues/4271
修复 PageView 范例，显示异常

fix PageView cases for fireball/issues/4271

---

assets/cases/02_ui/11_richtext/RichTextEvent.fire
assets/cases/03_gameplay/01_player_control/DeviceMotion.fire
assets/cases/03_gameplay/01_player_control/DeviceMotion/DeviceMotionCtrl.js
assets/cases/03_gameplay/02_actions/MoveAction.fire

https://github.com/cocos-creator/fireball/issues/4271

fix cases bug for fireball/issues/4271

---

assets/cases/03_gameplay/01_player_control/DeviceMotion/DeviceMotionCtrl.js

修复 https://github.com/cocos-creator/fireball/issues/4336

fix DeviceMotion example error for fireball/issues/4336

---

assets/cases/dragonbones/DragonBonesCtrl.js

Related issue : cocos-creator/fireball#4266

Solve the error in runtime environment.

---

assets/cases/anysdk/00_init.fire
assets/cases/anysdk/00_init.fire.meta
assets/cases/anysdk/00_init.meta
assets/cases/anysdk/00_init/Init.js
assets/cases/anysdk/00_init/Init.js.meta
assets/cases/anysdk/01_user.fire
assets/cases/anysdk/01_user/User.js
assets/cases/anysdk/02_iap.fire
assets/cases/anysdk/02_iap/IAP.js
assets/cases/anysdk/03_share.fire
assets/cases/anysdk/03_share/Share.js
assets/cases/anysdk/04_ads.fire
assets/cases/anysdk/04_ads/Ads.js
assets/cases/anysdk/05_analytics.fire
assets/cases/anysdk/05_analytics/Analytics.js
assets/cases/anysdk/06_social.fire
assets/cases/anysdk/06_social/Social.js
assets/cases/anysdk/07_push.fire
assets/cases/anysdk/07_push/Push.js
assets/cases/anysdk/08_adtracking.fire
assets/cases/anysdk/08_adtracking/AdTracking.js
assets/cases/anysdk/09_crash.fire
assets/cases/anysdk/09_crash/Crash.js
assets/cases/anysdk/10_rec.fire
assets/cases/anysdk/10_rec/REC.js
assets/cases/anysdk/AnySDKList.js
assets/i18n/data/en.js
assets/i18n/data/zh.js

cocos-creator/fireball#4366 
cocos-creator/fireball#4357

fix cocos-creator/fireball#4366 4357

---

assets/cases/collider/Shooter/Shooter.js
assets/cases/collider/Shooter/Shooter.js.meta
assets/scripts/Global/Menu.js
assets/scripts/Global/Menu.js.meta

1. 修复了子弹显示不出来的 bug
2. 由于 eventManager 注册事件已经不希望用户去用，所以修改为用 on 来注册事件
https://github.com/cocos-creator/fireball/issues/4383

fix Shooter bug for fireball/issues/4383

---

assets/cases/05_scripting/07_asset_loading/LoadResAll/loadResAll_example.js
assets/cases/05_scripting/07_asset_loading/LoadResAll/loadResAll_example.js.meta
assets/cases/anysdk/00_init/Init.js.meta
assets/cases/anysdk/01_user/User.js.meta
assets/cases/anysdk/02_iap/IAP.js.meta
assets/cases/anysdk/03_share/Share.js.meta
assets/cases/anysdk/04_ads/Ads.js.meta
assets/cases/anysdk/05_analytics/Analytics.js.meta
assets/cases/anysdk/06_social/Social.js.meta
assets/cases/anysdk/07_push/Push.js.meta
assets/cases/anysdk/08_adtracking/AdTracking.js.meta
assets/cases/anysdk/09_crash/Crash.js.meta
assets/cases/anysdk/10_rec/REC.js.meta
assets/cases/anysdk/AnySDKList.js.meta
assets/i18n/data/en.js.meta
assets/i18n/data/zh.js.meta

修复，用户频繁点击 loadResAll 会出现下方截图效果，并且会很卡
https://github.com/cocos-creator/fireball/issues/4417

fix loadResAll example error for fireball/issues/4417

---

assets/cases/01_graphics/01_sprite/AR.js.meta
assets/cases/05_scripting/03_events/EventInMask.fire
assets/cases/05_scripting/03_events/TouchDragger.js.meta
assets/cases/anysdk/00_init.meta
assets/cases/anysdk/00_init/Init.js.meta

https://github.com/cocos-creator/fireball/issues/4375

fix EventInMask bug for fireball/issues/4375

---

assets/cases/02_ui/05_scrollView/PageView/PageViewCtrl.js

https://github.com/cocos-creator/fireball/issues/4533

perfect pageView example for fireball/issues/4533

---

assets/cases/01_graphics/03_texture_format/webp-test.fire
assets/cases/05_scripting/07_asset_loading/LoadRes/LoadRes_example.js
assets/cases/05_scripting/07_asset_loading/LoadResAll.fire
assets/cases/05_scripting/07_asset_loading/LoadResAll/loadResAll_example.js

https://github.com/cocos-creator/fireball/issues/4538
https://github.com/cocos-creator/fireball/issues/4549

update loadResAll and webp-test 

---

assets/cases/05_scripting/10_loadingBar/LoadingBarCtrl.js

https://github.com/cocos-creator/fireball/issues/4538

fix 10_loadingBar error fix fireball/issues/4538

---

assets/cases/tiledmap/Puzzle.js

Related issue : cocos-creator/fireball#4547

The role should not be moved by touch when the game end layer is shown.

---

assets/cases/05_scripting/10_loadingBar/LoadingBarCtrl.js

切换场景，不会删除变量的赋值，导致没有进行重新计算进度条，就会出现第一次进入可正常加载，第二次进入一直处于加载过程中，未能成功加载出来
https://github.com/cocos-creator/fireball/issues/4538

fix LoadingBarCtrl bug for fireball/issues/4538

---

assets/cases/dragonbones/DragonBonesCtrl.js

Related issue : cocos-creator/fireball#4571

Solve the crash in native environment when re-enter DragonBones test case

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

https://github.com/cocos-creator/fireball/issues/4717

fix NetworkCtrl error #fireball/issues/4717

---

assets/cases/02_ui/15_mask.meta
assets/cases/02_ui/15_mask/Mask.meta
assets/cases/02_ui/15_mask/Mask/MaskCtrl.js
assets/cases/02_ui/15_mask/Mask/MaskCtrl.js.meta
assets/cases/02_ui/15_mask/Mask_ELLIPSE.fire
assets/cases/02_ui/15_mask/Mask_ELLIPSE.fire.meta
assets/cases/02_ui/15_mask/Mask_IMAGE_STENCIL.fire
assets/cases/02_ui/15_mask/Mask_IMAGE_STENCIL.fire.meta
assets/cases/02_ui/15_mask/Mask_RECT.fire
assets/cases/02_ui/15_mask/Mask_RECT.fire.meta

https://github.com/cocos-creator/fireball/issues/3961
添加 Mask 三个类型范例

add Mask example for #fireball/issues/3961

---

assets/TestList.fire
assets/scripts/Global/Menu.js

https://github.com/cocos-creator/fireball/issues/4585
优化了范例列表，把 TestList 变成常驻节点，切换场景的时候隐藏，返回当前主场景以后在显示

update Menu code for fireball/issues/4585

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/VideoPlayerCtrl.js
assets/cases/02_ui/09_videoplayer/videoPlayer.fire

修复 videoPlayer 测试语法不严谨造成的报错。
https://github.com/cocos-creator/fireball/issues/3473#issuecomment-266663551
@jareguo

Fixed a bug about video position error

---

assets/cases/native_call/Native_Call/NativeCallCtrl.js
build-templates/jsb-binary/frameworks/runtime-src/proj.android-studio/app/src/org/cocos2dx/javascript/AppActivity.java
build-templates/jsb-binary/frameworks/runtime-src/proj.android/src/org/cocos2dx/javascript/AppActivity.java
build-templates/jsb-default/frameworks/runtime-src/proj.android-studio/app/src/org/cocos2dx/javascript/AppActivity.java
build-templates/jsb-default/frameworks/runtime-src/proj.android/src/org/cocos2dx/javascript/AppActivity.java
build-templates/jsb-link/frameworks/runtime-src/proj.android-studio/app/src/org/cocos2dx/javascript/AppActivity.java
build-templates/jsb-link/frameworks/runtime-src/proj.android/src/org/cocos2dx/javascript/AppActivity.java

https://github.com/cocos-creator/fireball/issues/4907
@pandamicro

update NativeCallCtrl for example-calse

---

assets/cases/02_ui/15_mask/Mask/MaskCtrl.js
assets/cases/02_ui/15_mask/Mask_ELLIPSE.fire
assets/cases/02_ui/15_mask/Mask_IMAGE_STENCIL.fire
assets/cases/02_ui/15_mask/Mask_RECT.fire
assets/i18n/data/en.js
assets/i18n/data/zh.js
assets/res/textures/sheep/AutoAtlas.pac.meta
assets/scripts/Global/TipsManager.js

https://github.com/cocos-creator/fireball/issues/4897
完善 Mask 范例

fix Mask error for #fireball/issues/4897

---

assets/scripts/Global/Menu.js

修复场景还未加载完，点击返回菜单会出现场景列表显示错乱的 bug
https://github.com/cocos-creator/fireball/issues/4898

fix testList menu show error for #fireball/issues/4898

---

assets/cases/02_ui/02_label/LabelAtlas.fire
assets/resources/audio/cheering.wav.meta
assets/resources/audio/ding.wav.meta
assets/resources/audio/music_logo.mp3.meta
assets/resources/font/shuzibiaoqian03.labelatlas.meta
assets/resources/font/tuffy_bold_italic-charmap.labelatlas.meta
assets/resources/test assets/audio.mp3.meta

fix issue: https://github.com/cocos-creator/fireball/issues/5033

update labelatlas tests

---

assets/cases/dragonbones/DragonBonesCtrl.js

Related issue: cocos-creator/fireball#5006

Handle the TOUCH_CANCEL event of the direction buttons.

---

assets/scripts/Global/Menu.js

在主界面上返回列表按钮应该是不显示的才对
https://github.com/cocos-creator/fireball/issues/5043

fix btnBack error for fireball/issues/5043

---

assets/cases/05_scripting/11_network/NetworkCtrl.js
assets/cases/05_scripting/11_network/NetworkCtrl.js.meta
assets/cases/05_scripting/11_network/socket-io.js.meta

依赖 PR https://github.com/cocos-creator/fireball/pull/5090
不在编辑器中加载 socket.io

should not load socket.io in editor

---

assets/cases/dragonbones/DragonMesh.fire

Related issue: cocos-creator/fireball#5131

Make the node in test case DragonMesh at the center of screen.

---

assets/cases/05_scripting/07_asset_loading/LoadResDir/loadResDir_example.js

https://github.com/cocos-creator/fireball/issues/5137

fix example LoadResDir 'uuid is null ' error for #fireball/issues/5137

---

assets/cases/anysdk/10_rec/REC.js

https://github.com/cocos-creator/fireball/issues/5186
抱歉少改了一个..

fix 10_rec error for fireball/issues/5186

---

assets/cases/spine/SpineCtrl.js

Change the argument trackIndex to trackEntry.
Related issue: cocos-creator/fireball#5202

Modify the callback argument of spine event listener.

---

assets/cases/anysdk/BaseAnySDKExample.js

https://github.com/cocos-creator/fireball/issues/5197

update anysdk tips for fireball/issues/5197

---

assets/cases/03_gameplay/01_player_control/KeyboardInput/SimpleKeyboardMovement.js

http://forum.cocos.com/t/cocos-creator-v1-4-0-2-7-rc-2/41728/460
用户反馈 bug

fix SimpleKeyboardMovement bug

---

assets/cases/anysdk/01_user/User.js
assets/cases/anysdk/02_iap/IAP.js
assets/cases/anysdk/03_share/Share.js
assets/cases/anysdk/04_ads/Ads.js
assets/cases/anysdk/05_analytics/Analytics.js
assets/cases/anysdk/06_social/Social.js
assets/cases/anysdk/07_push/Push.js
assets/cases/anysdk/08_adtracking/AdTracking.js
assets/cases/anysdk/09_crash/Crash.js
assets/cases/anysdk/10_rec/REC.js

https://github.com/cocos-creator/fireball/issues/5211

fix anysdk tips error for #fireball/issues/5211

---

assets/cases/anysdk/01_user.fire
assets/cases/anysdk/02_iap.fire
assets/cases/anysdk/03_share.fire
assets/cases/anysdk/04_ads.fire
assets/cases/anysdk/05_analytics.fire
assets/cases/anysdk/06_social.fire
assets/cases/anysdk/07_push.fire
assets/cases/anysdk/08_adtracking.fire
assets/cases/anysdk/09_crash.fire
assets/cases/anysdk/10_rec.fire
assets/cases/anysdk/BaseAnySDKExample.js

调整 example case -> anysdk 提示问题
https://github.com/cocos-creator/example-cases/pull/327

fix cocos-creator/fireball/issues/5197

---

assets/cases/02_ui/15_mask/Mask/MaskCtrl.js.meta
assets/cases/02_ui/15_mask/Mask_NESTED.fire
assets/cases/05_scripting/11_network/socket-io.js.meta
assets/res/prefabs/TipsManager.prefab.meta

由于Canvas 不支持嵌套的 clipping，所以加了个提示
https://github.com/cocos-creator/fireball/issues/5458

fix cocos-creator/fireball/issues/5458

---

assets/cases/03_gameplay/03_animation/MoveAnimation.fire

统一调整按钮字体大小
https://github.com/cocos-creator/fireball/issues/5395

fix cocos-creator/fireball/issues/5395

---

assets/cases/spine/SpineCtrl.js
assets/cases/spine/SpineCtrl.js.meta

https://github.com/cocos-creator/fireball/issues/5673

fix spine demo bug for fireball/issues/5673

---

assets/cases/spine/SpineCtrl.js

完善 spine 范例，开枪后手上的枪应该回到起始动作
https://github.com/cocos-creator/fireball/issues/5673
@jareguo

perfect SpineBoy example for fireball/issues/5673

---

assets/cases/tiledmap/Puzzle.js

https://github.com/cocos-creator/fireball/issues/5661

fix Puzzle keyDown bug for fireball/issues/5661

---

assets/i18n/data/en.js
assets/i18n/data/zh.js

https://github.com/cocos-creator/fireball/issues/5197
添加更加明确的提示语

Add more explicit hints for fireball/issues/5197

---

assets/TestList.fire
assets/scripts/Global/Menu.js

https://github.com/cocos-creator/fireball/issues/5850

fix fireball/issues/5850

---

assets/cases/culling/culling.js

fixed https://github.com/cocos-creator/fireball/issues/5864#issuecomment-307005847

improve culling examples

---

assets/cases/02_ui/06_layout/Layout_None/Layout_None_Horizontal_Vertical.fire

https://github.com/cocos-creator/fireball/issues/5892

fix layout bug for fireball/issues/5892

---

assets/TestList.fire

https://github.com/cocos-creator/fireball/issues/5671
修复 example-case 点击查看说明按钮，界面显示异常

fix readme mask layout error for fireball/issues/5671

---

assets/cases/02_ui/08_editBox/EditBox.fire
assets/cases/02_ui/08_editBox/EditBoxTabIndex.fire

https://github.com/cocos-creator/fireball/issues/5188
屏幕适配问题

fix EditBox example for fireball/issues/5188

---

assets/TestList.fire
assets/scripts/Global/Menu.js

使用 cc.BlockInputEvents 简化弹出说明的遮挡实现
re: https://github.com/cocos-creator/fireball/issues/5483

use cc.BlockInputEvents

---

assets/TestList.fire
assets/scripts/Global/Menu.js

https://github.com/cocos-creator/fireball/issues/6126

Add restart & GC button

---

assets/cases/02_ui/08_editBox/EditBox.fire
assets/cases/02_ui/08_editBox/EditBoxTabIndex.fire
assets/scripts/Global/Menu.js

https://github.com/cocos-creator/fireball/issues/6104

fix editorbox example view instructions error for fireball/issues/6104

---

assets/cases/03_gameplay/01_player_control/DeviceMotion/DeviceMotionCtrl.js
assets/cases/tiledmap/Puzzle.js

destroy 是内部函数，不能乱用
https://github.com/cocos-creator/fireball/issues/6154
@nantas @jareguo @knoxHuang

#6154 Fixed destroy error

---

assets/cases/culling/culling.fire
assets/cases/culling/culling.js

https://github.com/cocos-creator/fireball/issues/6199
添加了根据渲染模式开启或者关闭 Camera 按钮

Add the Camera button according to the Render mode switch

---

assets/cases/culling/culling.fire
assets/cases/culling/cullingGraphics.js
assets/cases/culling/cullingGraphics.js.meta

https://github.com/cocos-creator/fireball/issues/6226
之前以为挂在 Graphics 节点的代码是多余的，所以把它删除了，现在把 culling 提取出创建 Graphics 的代码，免得误导用户为何要加 2 个 culling 在不同的节点上

add cullingGraphics fix fireball/issues/6226

---

assets/cases/02_ui/02_label/SystemFontLabel.fire
assets/cases/05_scripting/07_asset_loading/LoadRes/LoadRes_example.js

https://github.com/cocos-creator/fireball/issues/6224

Add label outline component

---

assets/cases/05_scripting/07_asset_loading/LoadResDir/loadResDir_example.js

https://github.com/cocos-creator/fireball/issues/6307

fix switch scene error when loading resource for fireball/issues/6307

---

assets/cases/02_ui/11_richtext/RichText.fire
assets/cases/02_ui/11_richtext/RichTextEvent.fire
assets/cases/02_ui/11_richtext/RichTextImage.fire
assets/res/textures/sheep/AutoAtlas.pac.meta
assets/resources/font/enligsh-chinese.fnt.meta
assets/resources/font/mikado_outline_shadow.fnt.meta
assets/resources/font/shuzibiaoqian03.labelatlas.meta
assets/resources/font/tuffy_bold_italic-charmap.labelatlas.meta
assets/resources/test assets/font.fnt.meta

https://github.com/cocos-creator/fireball/issues/6382

fix fireball/issues/6382

---

assets/scripts/Lib/cocosAnalytics.min.js.meta

for https://github.com/cocos-creator/fireball/issues/6422

import cocosAnallytics.min.js as web plugin

---

assets/cases/03_gameplay/01_player_control/OnTouchCtrl/OnTouchCtrl.js

https://github.com/cocos-creator/fireball/issues/6513

update 01_player_control cases for fireball/issues/6513

---

assets/cases/03_gameplay/03_animation/AnimationCallback.js
assets/cases/collider/Platform/HeroControl.js

https://github.com/cocos-creator/fireball/issues/6525

add off event to AnimationCallback case for fireball/issues/6525

---

assets/cases/05_scripting/04_scheduler/scheduleCallbacks.js

For cocos-creator/fireball#6518

Permit to test scheduler unscheduleAllCallbacks

---

assets/cases/02_ui/13_toggle/Toggle.fire

ToggleGroup replaced ToggleContainer

update Toggle cases

---

assets/cases/05_scripting/03_events/MousePropagation.fire

为 MousePropagation 测试项加 Tips
https://github.com/cocos-creator/fireball/issues/6602

fix fireball/issues/6602

---

assets/cases/03_gameplay/01_player_control/DeviceMotion/DeviceMotionCtrl.js

由于移除了 inputManager 所以替换成 systemEvent
@pandamicro 有空记得合并一下，thx

update DeviceMotionCtrl.js  cc.inputManager to cc.systemEvent for 

---

assets/cases/05_scripting/07_asset_loading/LoadRes/LoadRes_example.js

https://github.com/cocos-creator/fireball/issues/6709
@pandamicro 有空记得合并一下，thx

Improve LoadRes example for fireball/issues/6709

---

assets/cases/02_ui/08_editBox/EditBox.fire

https://github.com/cocos-creator/fireball/issues/5188

fix EditBox bug for fireball/issues/5188

---

assets/cases/05_scripting/07_asset_loading/LoadRes/LoadRes_example.js

for https://github.com/cocos-creator/fireball/issues/6757

fix asset release bug

---

assets/scripts/Global/Menu.js

https://github.com/cocos-creator/fireball/issues/6730

add cocosAnalytics.isInited code for fireball/issues/6730

---

assets/cases/dragonbones/DragonBones.fire
assets/cases/dragonbones/DragonBonesCtrl.js
assets/cases/graphics/demo/doodle.js
assets/cases/graphics/demo/sine-waves.js
assets/cases/graphics/example/arc.js
assets/cases/graphics/example/ellipse.js
assets/cases/graphics/example/lineTo.js
assets/cases/graphics/example/linejoin.js
assets/cases/graphics/example/rect.js

update dragonbones usage

---

assets/cases/02_ui/08_editBox/EditBox.fire
assets/cases/03_gameplay/02_actions/RotationAction.fire

https://github.com/cocos-creator/fireball/issues/6732

fix fireball/issues/6732

---

assets/cases/dragonbones/DragonBonesCtrl.js

https://github.com/cocos-creator/fireball/issues/6701

improve DragonBones example

---

assets/cases/tiledmap/Puzzle.js

https://github.com/cocos-creator/fireball/issues/6850

fixed puzzle example

---

assets/cases/05_scripting/11_network/network.fire
assets/cases/spine/SpineCtrl.js

for https://github.com/cocos-creator/fireball/issues/6850

Fix network test case label issue

---

assets/cases/motionStreak/MotionStreak.fire

https://github.com/cocos-creator/fireball/issues/6850

fixed motion streak

---

assets/cases/tiledmap/Puzzle.fire

for https://github.com/cocos-creator/fireball/issues/6937

Fix tilemap localizedLabel

---

assets/cases/02_ui/02_label/SystemFontLabel.fire
assets/cases/02_ui/05_scrollView/ListView.fire
assets/cases/02_ui/09_videoplayer/videoPlayer.fire
assets/cases/02_ui/10_webview/webview.fire
assets/cases/03_gameplay/03_animation/AnimationCallback.fire
assets/cases/collider/platform.fire
assets/cases/motionStreak/MotionStreak.fire

for https://github.com/cocos-creator/fireball/issues/6850

Improve example-cases for new renderer

---

assets/cases/02_ui/10_webview/webview.fire
assets/res/prefabs/TipsManager.prefab

https://github.com/cocos-creator/fireball/issues/6922

fix fireball/issues/6922

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/VideoPlayerCtrl.js

https://github.com/cocos-creator/fireball/issues/6886

fix fireball/issues/6886

---

assets/cases/camera/moving-objects.js

https://github.com/cocos-creator/fireball/issues/6988

fixed moving-objects

---

assets/cases/01_graphics/03_texture_format/webp-test.fire
assets/cases/03_gameplay/01_player_control/OnTouchInput.fire
assets/cases/05_scripting/11_network/network.fire

https://github.com/cocos-creator/fireball/issues/6988

fixed label

---

assets/cases/02_ui/09_videoplayer/fullscreenVideo.fire

For https://github.com/cocos-creator/fireball/issues/6988

Fix fullscreen video label issue

---

assets/cases/05_scripting/03_events/MousePropagation.fire

for https://github.com/cocos-creator/fireball/issues/6937

Add mobile platform notice for mouse propagation

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

improve network test

---

assets/cases/02_ui/05_scrollView/ListView/ListViewCtrl.js
assets/cases/02_ui/14_pageView/PageView/PageViewCtrl.js
assets/cases/03_gameplay/01_player_control/DeviceMotion/DeviceMotionCtrl.js
assets/cases/03_gameplay/01_player_control/OnTouchCtrl/OnTouchCtrl.js
assets/cases/03_gameplay/02_actions/MoveAction/MoveAction.js
assets/cases/03_gameplay/02_actions/SimpleAction/SimpleAction.js
assets/cases/05_scripting/02_prefab/PopulatePrefab.js
assets/cases/05_scripting/04_scheduler/scheduleCallbacks.js
assets/cases/05_scripting/08_module/LoadModuleCtrl.js
assets/cases/anysdk/tips/SuspensionTips.js
assets/cases/camera/culling.js
assets/cases/camera/cullingGraphics.js
assets/cases/dragonbones/DragonBonesCtrl.js
assets/cases/graphics/demo/doodle.js
assets/cases/graphics/example/arc.js
assets/cases/graphics/example/ellipse.js
assets/cases/graphics/example/lineTo.js
assets/cases/graphics/example/rect.js
assets/cases/tiledmap/Puzzle.js

https://github.com/cocos-creator/fireball/issues/7074

Upgrade deprecated APIs

---

assets/cases/02_ui/10_webview/webview.fire

Fix [#7043](https://github.com/cocos-creator/fireball/issues/7043)

修改 webview 测试项的提示信息。

---

assets/cases/02_ui/10_webview/webview.fire

https://github.com/cocos-creator/fireball/issues/7043

fix webview cases bug for fireball/issues/7043

---

assets/cases/05_scripting/07_asset_loading/LoadResDir/loadResDir_example.js
assets/resources/test assets/JSON.json
assets/resources/test assets/JSON.json.meta

for https://github.com/cocos-creator/fireball/issues/7210

add load json example

---

assets/cases/05_scripting/07_asset_loading/AssetLoading/AssetLoading.js

https://github.com/cocos-creator/fireball/issues/7241
更新 Assetloading 范例

update Assetloading cases

---

assets/cases/02_ui/10_webview/webview.fire

https://github.com/cocos-creator/fireball/issues/7252

fix webview tips error for fireball/issues/7252

---

assets/cases/05_scripting/07_asset_loading/AssetLoading/AssetLoading.js
assets/cases/05_scripting/07_asset_loading/LoadResDir/loadResDir_example.js

https://github.com/cocos-creator/fireball/issues/7245
调整一下 load text 和 load spriteframe 显示效果

fix AssetLoading and loadResDir example for fireball/issues/7245

---

assets/cases/07_render_texture/render_to_canvas.js

fiexed  https://github.com/cocos-creator/fireball/issues/7286 问题 9

fixed render_to_canvas bug

---

assets/cases/05_scripting/11_network/NetworkCtrl.js
assets/cases/05_scripting/11_network/socket-io.js
assets/i18n/LabelLocalized.js

https://github.com/cocos-creator/fireball/issues/7325
修复 socket-io 在微信上无效

fix socket-io invalid in wxgame for fireball/issues/7325

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/fullscreenVideoPlayer.js
assets/cases/02_ui/09_videoplayer/fullscreenVideo.fire
assets/cases/02_ui/09_videoplayer/videoPlayer.fire
assets/i18n/data/en.js
assets/i18n/data/zh.js

https://github.com/cocos-creator/fireball/issues/7320
1. 由于最新规则 video 没办法自动播放，所以修改了一下范例，通过点击按钮去执行全屏的 video 播放
2. 调整一下 video 的音量，1 在手机上太大声了，耳朵差点聋了

fix fireball/issues/7320, change video example

---

assets/cases/05_scripting/11_network/network.fire

https://github.com/cocos-creator/fireball/issues/7321

fix fireball/issues/7321

---

assets/cases/02_ui/10_webview/webview.fire

https://github.com/cocos-creator/fireball/issues/7043

fix fireball/issues/7043

---

assets/cases/02_ui/13_toggle/Toggle.fire

https://github.com/cocos-creator/fireball/issues/7410

fix toggle bug for fireball/issues/7410

---

assets/cases/01_graphics/01_sprite/ChangeColor.fire

https://github.com/cocos-creator/fireball/issues/7410

fixed ChangeColor cases for fireball/issues/7410

---

assets/cases/05_scripting/07_asset_loading/LoadResDir/loadResDir_example.js

re: https://github.com/cocos-creator/fireball/issues/7410

fixed loadResDir example

---

assets/cases/05_scripting/11_network/socket-io.js
assets/i18n/LabelLocalized.js

https://github.com/cocos-creator/fireball/issues/7418

fix socket-io for fireball/issues/7418

---

assets/cases/07_render_texture/render_to_canvas.js

https://github.com/cocos-creator/fireball/issues/7418

fixed screen capture error on wechat platform

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/fullscreenVideoPlayer.js
assets/cases/02_ui/09_videoplayer/fullscreenVideo.fire

https://github.com/cocos-creator/fireball/issues/7587
https://github.com/cocos-creator/fireball/issues/7583

fixed fireball/issues/7587

---

assets/cases/02_ui/15_mask/Mask_IMAGE_STENCIL.fire
assets/cases/02_ui/15_mask/Mask_NESTED.fire

https://github.com/cocos-creator/fireball/issues/7631

fix cocos-creator/fireball#7631

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

unregistered XMLHttpRequest eventlistener to network

---

assets/cases/camera/culling.fire

https://github.com/cocos-creator/fireball/issues/7670

fix cocos-creator/fireball/issues/7670

---

assets/cases/01_graphics/03_texture_format/webp-test.fire
assets/cases/02_ui/02_label/SystemFontLabel.fire
assets/cases/02_ui/08_editBox/EditBoxTabIndex.fire
assets/cases/02_ui/09_videoplayer/fullscreenVideo.fire
assets/cases/02_ui/09_videoplayer/videoPlayer.fire
assets/cases/02_ui/10_webview/webview.fire
assets/cases/02_ui/15_mask/Mask_IMAGE_STENCIL.fire
assets/cases/02_ui/15_mask/Mask_NESTED.fire
assets/cases/03_gameplay/01_player_control/DeviceMotion.fire
assets/cases/03_gameplay/01_player_control/KeyboardInput.fire
assets/cases/03_gameplay/01_player_control/OnMultiTouchInput.fire
assets/cases/03_gameplay/01_player_control/OnTouchInput.fire
assets/cases/04_audio/SimpleAudio.fire
assets/cases/05_scripting/03_events/MousePropagation.fire
assets/cases/anysdk/AnySDKList.js
assets/cases/collider/platform.fire
assets/cases/dragonbones/DragonBones.fire
assets/cases/motionStreak/MotionStreak.fire
assets/cases/native_call/Native_Call.fire
assets/cases/tiledmap/Puzzle.fire
assets/res/prefabs/TipsManager.prefab
assets/scripts/Global/TipsManager.js
settings/builder.json

完善一下范例提示功能
https://github.com/cocos-creator/fireball/issues/7651

 improve tips for fireball/issues/7651

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/fullscreenVideoPlayer.js
assets/cases/02_ui/09_videoplayer/fullscreenVideo.fire
assets/i18n/data/en.js
assets/i18n/data/zh.js
settings/builder.json

https://github.com/cocos-creator/fireball/issues/7652

fix cocos-creator/fireball/issues/7652

---

assets/cases/04_audio/SimpleAudio.fire

resume audio

---

build-templates/jsb-binary/frameworks/runtime-src/proj.android/src/org/cocos2dx/javascript/AppActivity.java
build-templates/jsb-default/frameworks/runtime-src/proj.android/src/org/cocos2dx/javascript/AppActivity.java
build-templates/jsb-link/frameworks/runtime-src/proj.android/src/org/cocos2dx/javascript/AppActivity.java

Re:#488
This pr is connected to an old issue, https://github.com/cocos-creator/cocos2d-x-lite/pull/808
now in the Android platform still has that problem

fixed the relaunch game will get break  problem

---

assets/cases/05_scripting/03_events/MouseDragger.js
assets/cases/dragonbones/DragonBonesCtrl.js

https://github.com/cocos-creator/fireball/issues/7682
https://github.com/cocos-creator/fireball/issues/7688

Fix event issues

---

assets/cases/04_audio/AudioEngineControl.js

https://github.com/cocos-creator/fireball/issues/7721

update audio example-case fix fireball/issues/7721

---

assets/cases/02_ui/03_button/ButtonInScroll.fire
assets/res/prefabs/ListItem.prefab
assets/res/prefabs/ListItem.prefab.meta
assets/res/textures/ui/style1/btn_options.png.meta
assets/res/textures/ui/style1/btn_play.png.meta
assets/res/textures/ui/style1/panelBG.png.meta

关联 pr: https://github.com/cocos-creator/fireball/issues/7692
log: 部分资源没有预乘导致出现黑边

fix cocos-creator/fireball/issues/7692

---

assets/cases/06_rendering/01_custom_ia/ColorRect.js
assets/cases/06_rendering/01_custom_ia/ColorRectAssembler.js

https://github.com/cocos-creator/fireball/issues/7075

Fix renderer usage issue before engine init

---

assets/cases/04_audio/AudioEngineControl.js

完善一下 audio 代码 
修复相关 pr: https://github.com/cocos-creator/fireball/issues/7763

update audio example fireball/issues/7763

---

assets/cases/02_ui/08_editBox/EditBox.fire
assets/cases/02_ui/08_editBox/EditBoxTabIndex.fire

修复相关 issue： https://github.com/cocos-creator/fireball/issues/7788
完善一下 EditorBox 范例

fix fireball/issues/7788

---

assets/cases/02_ui/10_webview/webview.fire

Re: cocos-creator/fireball#7515
修复的问题是，
webview 场景中，editbox TEXT_LABEL 节点 的 label 组件被 unenabled 了
所以这个 TEXT_LABEL 节点，怎么也看不到内容
@jareguo

fix webview editBox label invisible

---

assets/cases/05_scripting/11_network/DownloaderCtrl.js
assets/cases/05_scripting/11_network/downloader.fire

https://github.com/cocos-creator/fireball/issues/7817

Use new url for downloadText

---

assets/cases/03_gameplay/01_player_control/DeviceMotion/DeviceMotionCtrl.js

Re: cocos-creator/fireball#7846

stop coin move when unenabled motionDeviceEvent

---

assets/cases/07_render_texture/render_to_canvas.fire

render_to_canvas 的 camera 也需要去掉多余的 stencil 的 clear flag
https://github.com/cocos-creator/fireball/issues/7698

fixed render_to_canvas

---

assets/cases/02_ui/08_editBox/EditBox.fire
assets/cases/03_gameplay/02_actions/RotationAction.fire

修复 https://github.com/cocos-creator/fireball/issues/7858
editbox的单行密码框的边框 与 Rotation Action测试项的边框错误的 bug

fix fireball/issues/7858 issues 2

---

assets/res/prefabs/ListItem.prefab

https://github.com/cocos-creator/fireball/issues/7692
解决图片预乘 bug

fixed fireball/issues/7692

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/FullscreenVideoPlayerEvent.js
assets/cases/02_ui/09_videoplayer/VideoPlayer/FullscreenVideoPlayerEvent.js.meta
assets/cases/02_ui/09_videoplayer/VideoPlayer/fullscreenVideoPlayer.js
assets/cases/02_ui/09_videoplayer/fullscreenVideo.fire
assets/i18n/data/en.js
assets/i18n/data/zh.js
assets/resources/prefabs.meta
assets/resources/prefabs/VideoPlayer.prefab
assets/resources/prefabs/VideoPlayer.prefab.meta

improve FullscreenVideo example

---

assets/cases/02_ui/02_label/TTFFontLabel.fire
assets/cases/02_ui/02_label/TTFFontLabel.fire.meta
assets/scripts/Global/Menu.js
assets/scripts/Tips/TipsManager.js

https://github.com/cocos-creator/fireball/issues/7896
https://github.com/cocos-creator/example-cases/issues/524
效果图：

add TTFFontlabel example-case

---

assets/scripts/Tips/TipsManager.js

Re: cocos-creator/fireball#7962
小游戏平台不支持 render_to_canvas
@knoxHuang

wechatgame not surpport render_to_canvas

---

assets/TestList.fire
assets/cases/02_ui/03_button/ButtonInScroll.fire
assets/cases/02_ui/15_mask/Mask_IMAGE_STENCIL.fire
assets/cases/02_ui/15_mask/Mask_NESTED.fire
assets/cases/05_scripting/11_network/downloader.fire
assets/cases/spine/SpineMesh.fire
assets/res/imported/particle/atom.plist.meta
assets/res/imported/particle/smoke.plist.meta
assets/res/prefabs/SuspensionTips.prefab.meta
assets/res/prefabs/loadAnimTest.prefab.meta
assets/res/prefabs/loadItem.prefab.meta
assets/res/prefabs/rightSprite.prefab.meta
assets/resources/spineRaptor/raptor.png.meta
assets/resources/test assets/atom.plist.meta
settings/builder.json

https://github.com/cocos-creator/fireball/issues/7953

Fix stencil flag in scenes with mask

---

assets/scripts/Tips/TipsManager.js

修改 ttf 测试例，支持 小游戏  和 native
关联 pr: 
https://github.com/cocos-creator/cocos2d-x-lite/pull/1423
@knoxHuang

update ttf in tipsManager

---

assets/cases/05_scripting/11_network/DownloaderCtrl.js
assets/cases/05_scripting/11_network/downloader.fire

https://github.com/cocos-creator/fireball/issues/7938

Add download image to memory test

---

assets/cases/02_ui/08_editBox/EditBox.fire

Re: cocos-creator/fireball#8030
修复edibox 事件绑定问题

fix editbox eventHandler binding

---

assets/cases/anysdk/08_adtracking.fire

Re:#469
#546
关联一下，这是之前场景内没有改好的脚本文件引用

correct scriptName "AdTracking" mismatch

---

assets/cases/01_graphics/01_sprite/AR.js
assets/cases/01_graphics/01_sprite/ChangeColor.js
assets/cases/02_ui/08_editBox/EditBox.fire
assets/cases/02_ui/08_editBox/EditBoxTabIndex.fire
assets/cases/02_ui/09_videoplayer/VideoPlayer/FullscreenVideoPlayerEvent.js
assets/cases/02_ui/10_webview/WebviewCtrl.js
assets/cases/03_gameplay/03_animation/SpriteAnimation/SheepAnimationCtrl.js
assets/cases/05_scripting/03_events/CustomEvent.js
assets/cases/05_scripting/03_events/MouseEvent.js
assets/cases/05_scripting/03_events/TouchEvent.js
assets/cases/05_scripting/04_scheduler/scheduleCallbacks.js
assets/cases/05_scripting/07_asset_loading/AssetLoading/ComeBackToAssetLoad.js
assets/cases/collider/Category/ColliderListener.js
assets/cases/collider/Shape/ShowCollider.js
assets/cases/graphics/RuntimeLabel.js

1. 修复一个错误场景 EditBoxTapIndex
2. 修改一些脚本，但实际不影响功能

Adjust Scene js files

---

assets/cases/02_ui/11_richtext/RichText.fire
assets/cases/02_ui/11_richtext/RichTextEvent.fire
assets/cases/02_ui/11_richtext/RichTextImage.fire

https://github.com/cocos-creator/fireball/issues/8049

update richtext example

---

assets/scripts/Tips/TipsManager.js

Re: cocos-creator/fireball#8064

add subpackage case support

---

assets/scripts/Tips/TipsManager.js

correct TipsManager its limit on video

correct Tips make the video scene can open in the android platform

---

assets/cases/05_scripting/03_events/HideOrShowEvent.fire
assets/cases/05_scripting/03_events/HideOrShowEvent.fire.meta
assets/cases/05_scripting/03_events/HideOrShowEvent.js
assets/cases/05_scripting/03_events/HideOrShowEvent.js.meta
assets/res/prefabs/HideOrShowEventLogItem.prefab
assets/res/prefabs/HideOrShowEventLogItem.prefab.meta

Re: cocos-creator/fireball#8104
增加 EVENT_HIDE/ EVENT_SHOW 测试例

add game hide/show event test case

---

assets/scripts/Tips/TipsManager.js

https://github.com/cocos-creator/fireball/issues/7807 
（mobile browers 没什么问题）

video play in the native forbid temporarily

---

assets/cases/05_scripting/03_events/HideOrShowEvent.fire
assets/cases/05_scripting/03_events/HideOrShowEvent.js
assets/cases/05_scripting/03_events/HideOrShowEventLogItem.js
assets/cases/05_scripting/03_events/HideOrShowEventLogItem.js.meta
assets/res/prefabs/HideOrShowEventLogItem.prefab
assets/res/prefabs/HideOrShowEventLogItem.prefab.meta

Re: https://github.com/cocos-creator/fireball/issues/8171
我的锅，忘了在 onDestroy 里边取消 事件注册了
顺便调整了 测试例的 UI 显示问题

unregister event show / hide onDestroy

---

assets/cases/anysdk/AnySDKList.js
assets/scripts/Tips/TipsManager.js

修复了勾选 anysdk 后，其他场景无法打开问题。
fixed the problem that when the user chooses the anysdk then cannot open others Scene in mobiles.

fixed  tipsManager setting relative to the anysdk

---

assets/cases/07_render_texture/render_to_canvas.fire
assets/cases/07_render_texture/render_to_canvas.js

Re: cocos-creator/fireball#8200

Test capturing mask in render to canvas

---

assets/cases/02_ui/05_scrollView/ListView.fire
assets/cases/02_ui/05_scrollView/ScrollView.fire
assets/cases/02_ui/06_layout/Layout_None/Layout_None_Basic.fire
assets/cases/02_ui/06_layout/Layout_None/Layout_None_Grid.fire
assets/cases/02_ui/06_layout/Layout_None/Layout_None_Horizontal_Vertical.fire
assets/cases/02_ui/06_layout/Layout_ResizeChildren/Layout_ResizeChildren_Grid.fire
assets/cases/02_ui/06_layout/Layout_ResizeChildren/Layout_ResizeChildren_Normal.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Basic.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Grid.fire
assets/cases/02_ui/06_layout/Layout_ResizeContainer/Layout_ResizeContainer_Normal.fire
assets/cases/02_ui/06_layout/Layout_ScrollView/Layout_ScrollViewGrid.fire
assets/cases/02_ui/06_layout/Layout_ScrollView/Layout_ScrollViewNormal.fire
assets/cases/02_ui/08_editBox/EditBox.fire
assets/cases/02_ui/08_editBox/EditBoxTabIndex.fire
assets/cases/02_ui/12_slider/Slider.fire
assets/cases/02_ui/14_pageView/PageView_Free_Horizontal.fire
assets/cases/02_ui/14_pageView/PageView_Free_Vertical.fire
assets/cases/02_ui/14_pageView/PageView_Unified_Horizontal.fire
assets/cases/02_ui/14_pageView/PageView_Unified_Vertical.fire
assets/cases/02_ui/15_mask/Mask_ELLIPSE.fire
assets/cases/02_ui/15_mask/Mask_RECT.fire
assets/cases/05_scripting/03_events/EventInMask.fire
assets/cases/05_scripting/07_asset_loading/AssetLoading.fire
assets/cases/05_scripting/07_asset_loading/LoadResDir.fire
assets/cases/05_scripting/08_module/load_module.fire
assets/cases/05_scripting/10_loadingBar/loadingBar.fire
assets/cases/07_render_texture/render_to_canvas.fire

Fixed https://github.com/cocos-creator/fireball/issues/8333

Fix camera clear flags not clearing stencil issue

---

assets/cases/02_ui/15_mask/Mask_NESTED.fire

https://github.com/cocos-creator/fireball/issues/8356

Modify inner mask to inverted mask

---

assets/cases/05_scripting/11_network/downloader-native.fire
assets/cases/05_scripting/11_network/downloader-native/DownloaderCtrl.js

https://github.com/cocos-creator/fireball/issues/8346
修复并且调整 network-native

improve network-native example for fireball/issues/8346

---

assets/scripts/Global/SceneList.js

fix https://github.com/cocos-creator/fireball/issues/8397

fix sequence of scene

---

assets/cases/05_scripting/11_network/downloader-web.fire

https://github.com/cocos-creator/fireball/issues/8395
https://github.com/cocos-creator/fireball/issues/8345
上面 2 个 issue 的 bug，是因为 content 上 widget 组件使用的是 on_windows_resize 的模式，导致点击输入框弹出键盘会触发 window 的重新布局导致又把 content 的坐标重置到最初的坐标点

fix downloader-web bug for fireball/issues/8395 or 8345

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

https://github.com/cocos-creator/fireball/issues/8428
延长 timeout 时间为 10

extend the timeout time to 10 seconds for fireball/issues/8428

---

assets/TestList.fire
assets/main menu/Menu.js
assets/main menu/StorageUtil.js
assets/main menu/StorageUtil.js.meta

1. 增加一个保存最后退出场景功能，仅在 Preview 模式下有效

add the feature to record the last close scene url

---

assets/scripts/Tips/TipsManager.js

Re: https://github.com/cocos-creator/2d-tasks/issues/613

close the DeviceMotion in Android

---

assets/cases/02_ui/05_scrollView/ListView/ListViewCtrl.js

https://github.com/cocos-creator/2d-tasks/issues/630
关联pr： 
https://github.com/cocos-creator/example-cases/pull/586

fix listView removeItem for v1.10-release

---

assets/cases/05_scripting/11_network/socket-io.js

修复 issue：https://github.com/cocos-creator/2d-tasks/issues/459

fix socket-io no es6 change to es5 for 2d-tasks/issues/459

---

assets/cases/02_ui/03_button/ButtonInteractable.meta
assets/cases/02_ui/03_button/ButtonTransition.fire
assets/cases/02_ui/03_button/ButtonTransition/ButtonTransition.js

补充： https://github.com/cocos-creator/example-cases/pull/605
- 删除 buttonInteractable.meta 文件
- 补充 buttonTransition 的 scale 模式
@jareguo

remove buttonInteractable.meta & add scale in buttonTransition

---

assets/scripts/Tips/TipsManager.js

cocos-creator/2d-tasks#639
@knoxHuang please review

enable webview & videoplayer test cases on Native Mobile

---

assets/TestList.fire

Re: https://github.com/cocos-creator/2d-tasks/issues/670
seachBlock 父级节点不是 Scene 导致 addPersistRootNode API 警告。
已修复
修改层级关系。

adjust SearchBlock node hierarchical  relationship

---

assets/cases/02_ui/10_webview/webview.fire

调整一下场景参数，昨天修 label 显示的 bug 的时候改了参数忘记调整回来了。。。

adjust the scene agine

---

assets/cases/02_ui/10_webview/webview.fire

https://github.com/cocos-creator/2d-tasks/issues/683
调整一下 webview 输入框的大小

improve WebView editor box size for cocos-creator/2d-tasks/issues/683

---

assets/cases/07_capture_texture/capture_to_native.js

fixed the capture_to_native save failed problem

---

assets/main menu/Menu.js

添加检测加载场景是否成功，如果不成功，应该清除本地缓存场景的数据

add check whether the loading scenario is successful

---

assets/i18n/data/en.js
assets/i18n/data/zh.js

Re: https://github.com/cocos-creator/2d-tasks/issues/720

modify the changColor note

---

assets/cases/3d/mesh-texture.js
assets/cases/3d/mesh.js

https://github.com/cocos-creator/2d-tasks/issues/722

refine apis

---

assets/cases/01_graphics/02_particle/ToggleParticle.fire
assets/cases/02_ui/03_button/ButtonTransition.fire
assets/cases/03_gameplay/02_actions/SequenceAction/SequenceAction.js
assets/cases/collider/Utils/SimpleMotion.js

修复一些范例的警告例如 rotation 需要改为 angle， cc.p 改为 cc.v2 等问题

refine example

---

assets/TestList.fire
assets/main menu/back icon.png.meta
assets/main menu/eject_btn.png.meta
assets/main menu/search_btn.png.meta
assets/res/prefabs/Center Menu.prefab
assets/res/prefabs/Center Menu.prefab.meta
assets/res/prefabs/Left Menu.prefab
assets/res/prefabs/Left Menu.prefab.meta
assets/res/prefabs/Right Menu.prefab
assets/res/prefabs/Right Menu.prefab.meta
assets/res/prefabs/Search Block.prefab
assets/scripts/ComponentUtils/SearchBlock.js

1. 调整场景样式，将 button 都做成了 prefab
2. 引用 button 图片开启预乘
3. 调整 searchBlock 样式

adjust Test Scene and prefab

---

assets/TestList.fire
assets/cases/3d/raycast.fire
assets/res/prefabs/Center Menu.prefab.meta
assets/res/prefabs/Left Menu.prefab.meta
assets/res/prefabs/Right Menu.prefab.meta
assets/res/prefabs/Search Block.prefab

https://github.com/cocos-creator/2d-tasks/issues/763

set the Search Block group to ui for 2d-tasks/issues/763

---

assets/TestList.fire
assets/cases/07_capture_texture/capture_to_native.fire
assets/cases/07_capture_texture/capture_to_web.fire
assets/cases/07_capture_texture/capture_to_wechat.fire
assets/res/prefabs/Center Menu.prefab
assets/res/prefabs/Left Menu.prefab
assets/res/prefabs/Right Menu.prefab
assets/res/prefabs/Search Block.prefab

启用菜单按钮预乘，避免黑边
统一场景搜索框视觉样式
几个 capture xxx 的场景背景颜色不统一，统一加上了 Background prefab 了

beautify menus

---

assets/scripts/Tips/TipsManager.js

https://github.com/cocos-creator/engine/pull/3534

restore webview/video on ios/android native support

---

assets/cases/07_capture_texture/capture_to_native.fire
assets/cases/07_capture_texture/capture_to_native.js
assets/cases/07_capture_texture/capture_to_web.fire
assets/cases/07_capture_texture/capture_to_web.js
assets/cases/07_capture_texture/capture_to_wechat.fire
assets/cases/07_capture_texture/capture_to_wechat.js
assets/cases/07_capture_texture/textureRenderUtils.js
assets/scripts/Tips/TipsManager.js

1. 限制 iosSafeRect 场景，只在 native 平台有效
2. 调整 capture 截屏效果, 除了微信平台， native web 平台截屏以这个效果为准
3. 去除了 web 平台图片下载。
Re: https://github.com/cocos-creator/2d-tasks/issues/719
Re: https://github.com/cocos-creator/2d-tasks/issues/770
Re: https://github.com/cocos-creator/2d-tasks/issues/761

Adjust scene

---

assets/cases/07_capture_texture/textureRenderUtils.js

Re: https://github.com/cocos-creator/2d-tasks/issues/819
修复场景关于调用了 scene.active 的报错。
修复动图：

fixed the scene runAction error

---

assets/cases/02_ui/09_videoplayer/VideoPlayerCtrl.js
assets/cases/02_ui/09_videoplayer/videoPlayer.fire
assets/cases/02_ui/09_videoplayer/videoPlayer.fire.meta

https://github.com/cocos-creator/2d-tasks/issues/828

fix videoplayer play error for 2d-tasks/issues/828

---

assets/cases/03_gameplay/02_actions/Rotation/RotationCtrl.js

https://github.com/cocos-creator/2d-tasks/issues/848

fix rotation invalid for 2d-tasks/issues/848

---

assets/scripts/Tips/TipsManager.js

Re: https://github.com/cocos-creator/2d-tasks/issues/866
在百度、微信小游戏平台上禁用一些测试例
包括 键盘事件、videoplayer

ban some cases on BAIDU_GAME

---

assets/cases/07_capture_texture/capture_to_native.fire
assets/cases/07_capture_texture/capture_to_native.js
assets/cases/07_capture_texture/capture_to_web.fire
assets/cases/07_capture_texture/capture_to_web.js
assets/cases/07_capture_texture/capture_to_wechat.fire
assets/cases/07_capture_texture/capture_to_wechat.js
assets/cases/07_capture_texture/textureRenderUtils.js

Re: https://github.com/cocos-creator/2d-tasks/issues/887
adjust cc.log as the console.log, the problem of cc.log (CCDebugMode) still need to be detected.
cherry pick from the 2.1

capture scene adjust

---

assets/scripts/Tips/TipsManager.js

issue： https://github.com/cocos-creator/2d-tasks/issues/841
封闭相关平台场景测试。

restricted the vivo and oppo scene permissions

---

assets/scripts/Tips/TipsManager.js

https://github.com/cocos-creator/2d-tasks/issues/963
添加分包不支持 native 平台 tips

add subpackages not support native tips

---

assets/scripts/Tips/TipsManager.js

https://github.com/cocos-creator/2d-tasks/issues/967
https://github.com/cocos-creator/2d-tasks/issues/969

improve tipsManager code

---

assets/cases/05_scripting/04_scheduler/recursiveTask.js
assets/scripts/Tips/TipsManager.js

1.修改 require LabelLocalized 路径
2.添加子包不支持 web 的提示

refine require LabelLocalized url and subpackage no support web

---

assets/scripts/Tips/TipsManager.js

屏蔽子包 https://github.com/cocos-creator/2d-tasks/issues/1010
屏蔽 Downloader_native、Native_call https://github.com/cocos-creator/2d-tasks/issues/961
屏蔽 重力感应 https://github.com/cocos-creator/2d-tasks/issues/968

update tipsManager sub-package name

---

assets/cases/02_ui/10_webview/webview.fire
assets/cases/05_scripting/11_network/NetworkCtrl.js

issue: https://github.com/cocos-creator/2d-tasks/issues/1002
余留了 socketio 连接失效的问题。socketio 的链接不是很好修改，目前就没做调整了
https://blog.csdn.net/wypeng2010/article/details/84650225
解决方案可以参考的尝试一下。

Adjusting network url to avoid the response failing in Android

---

assets/cases/05_scripting/03_events/BasicEventTest.fire
assets/cases/05_scripting/03_events/BasicEventTest.fire.meta
assets/cases/05_scripting/03_events/BasicEventTest.meta
assets/cases/05_scripting/03_events/BasicEventTest/BasicEventCtrl.js
assets/cases/05_scripting/03_events/BasicEventTest/BasicEventCtrl.js.meta

Re: https://github.com/cocos-creator/2d-tasks/issues/1060
新增一个节点基本监听事件测试场景

add a basic event listent scene

---

assets/scripts/Tips/TipsManager.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1086
百度平台禁用 videoPlayer 测试例，

ban videoPlayer on baidu game

---

assets/cases/05_scripting/03_events/BasicEventTest.fire
assets/cases/05_scripting/03_events/BasicEventTest/BasicEventCtrl.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1123
加强场景效果，便于 QA 确认功能生效

Update the basicEvent scene effect

---

assets/cases/dragonbones/DragonBones.fire

Re: https://github.com/cocos-creator/2d-tasks/issues/1139
调整了 overflow 类型，应该不会再有字体超出的情况了

modify the button label overflow setting

---

assets/cases/05_scripting/03_events/BasicEventTest/BasicEventCtrl.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1160
调整 childNode 的相关测试结果提示样式

modify the childrenNode order result tips

---

assets/cases/05_scripting/07_asset_loading/AssetLoading/AssetLoading.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1156
修复 example caase/ assetLoading 测试例，  
切换场景时，没有释放已经加载的资源，导致后续加载出现问题

fix assetLoading releaseAsset

---

build-templates/android-instant/frameworks/runtime-src/proj.android-studio/game/src/org/cocos2dx/javascript/AppActivity.java

add activity template for sample
https://github.com/cocos-creator/2d-tasks/issues/1146

add activity template for sample

---

assets/cases/05_scripting/07_asset_loading/AssetLoading/AssetLoading.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1197

fix release curRes twice in assetLoading

---

assets/cases/05_scripting/07_asset_loading/AssetLoading/AssetLoading.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1199

fix release 'null' asset

---

build-templates/android-instant/frameworks/runtime-src/proj.android-studio/game/src/org/cocos2dx/javascript/AppActivity.java

change activity code instant sample

change activity code instant sample

---

assets/cases/05_scripting/11_network/downloader-native/DownloaderCtrl.js
assets/cases/05_scripting/11_network/network.fire.meta

cocos-creator/2d-tasks/issues/1203

fix downloader-native bug cocos-creator/2d-tasks/issues/1203

---

assets/cases/collider/Utils/PlatformMotion.js

remove useless code.

---

assets/cases/03_gameplay/tween.meta
assets/cases/03_gameplay/tween/tween-demo.fire
assets/cases/03_gameplay/tween/tween-demo.fire.meta
assets/cases/03_gameplay/tween/tween-demo.js
assets/cases/03_gameplay/tween/tween-demo.js.meta

需要 https://github.com/cocos-creator/engine/pull/3984 先合并

add tween demo

---

assets/cases/05_scripting/10_loadingBar/LoadingBarCtrl.js

释放所有依赖资源
https://github.com/cocos-creator/engine/pull/3935
其他地方都已经用getDependsRecursively获取依赖资源并释放

release all dependencies

---

assets/cases/04_audio/AudioEngine.fire.meta
assets/cases/04_audio/AudioEngineControl.js

re: https://github.com/cocos-creator/2d-tasks/issues/1270
切换场景时，audioEngine 停止播放，且自动释放资源

stop audioEngine on scene destroy && add scene autoReleaseAssets

---

assets/cases/02_ui/02_label/OutlineLabel.fire
assets/cases/02_ui/02_label/OutlineLabel.fire.meta
assets/cases/02_ui/02_label/ShadowLabel.fire
assets/cases/02_ui/02_label/ShadowLabel.fire.meta
assets/scripts/Tips/TipsManager.js

https://github.com/cocos-creator/2d-tasks/issues/138

add Shadow and Outline case

---

assets/cases/02_ui/12_slider/Slider.fire

https://github.com/cocos-creator/engine/pull/4163
添加 slider 有关锚点设置的测试用例

update slider case

---

assets/cases/3d/3d-model.fire
assets/cases/3d/3d-model.fire.meta
assets/cases/3d/dynamic-load-material.fire
assets/cases/3d/dynamic-load-material.fire.meta
assets/cases/3d/dynamic-load-material.js
assets/cases/3d/dynamic-load-material.js.meta
assets/cases/3d/mesh-texture.fire.meta
assets/cases/3d/raycast.fire
assets/cases/3d/raycast.fire.meta
assets/cases/3d/raycast.js

https://github.com/cocos-creator/2d-tasks/issues/1262
https://github.com/cocos-creator/2d-tasks/issues/1258

refine 3d scene

---

assets/cases/05_scripting/11_network/downloader-native.fire
assets/cases/05_scripting/11_network/downloader-native.fire.meta
assets/cases/05_scripting/11_network/downloader-native/DownloaderCtrl.js

https://github.com/cocos-creator/2d-tasks/issues/1322

fix downloader-native case for cocos-creator/2d-tasks/issues/1322

---

assets/scripts/Tips/TipsManager.js

https://github.com/cocos-creator/2d-tasks/issues/1342
ShadowLabel测试项只在 web 中有效果

fix cocos-creator/2d-tasks/issues/1342

---

assets/scripts/Tips/TipsManager.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1323
禁止部分平台在 huawei 小游戏开启场景

forbid several scenes to load in huawei platform

---

assets/cases/05_scripting/11_network/socket-io.js.meta
assets/resources/materials.meta

Reverts cocos-creator/example-cases#714

Revert "fix socket-io bug for cocos-creator/2d-tasks/issues/1336"

---

assets/cases/3d/dynamic-load-material.js

https://github.com/cocos-creator/2d-tasks/issues/1366

fixed dynamic-load-material example

---

assets/scripts/Tips/TipsManager.js

重新提交 https://github.com/cocos-creator/example-cases/pull/713

simplify tipsManager && add xiaomi platform checking

---

.gitignore
assets/cases/native_call/Native_Call/NativeCallCtrl.js
build-templates/jsb-default/frameworks/runtime-src/proj.ios_mac/ios/AppController.h
build-templates/jsb-default/frameworks/runtime-src/proj.ios_mac/ios/AppController.mm
build-templates/jsb-link/frameworks/runtime-src/proj.ios_mac/ios/AppController.h
build-templates/jsb-link/frameworks/runtime-src/proj.ios_mac/ios/AppController.mm

add Native Call to IOS

---

assets/main menu/Menu.js

https://github.com/cocos-creator/2d-tasks/issues/1413
这个已经在 2.1.1 中修复了，同步过来

remove redundant code

---

assets/scripts/Tips/TipsManager.js

添加 华为快游戏 tips 
https://github.com/cocos-creator/2d-tasks/issues/1417

add huawei to tipeManager

---

assets/cases/06_rendering/custom_material.meta
assets/cases/06_rendering/custom_material/custom_material.effect
assets/cases/06_rendering/custom_material/custom_material.effect.meta
assets/cases/06_rendering/custom_material/custom_material.fire
assets/cases/06_rendering/custom_material/custom_material.fire.meta
assets/cases/06_rendering/custom_material/custom_material.js
assets/cases/06_rendering/custom_material/custom_material.js.meta
assets/cases/06_rendering/custom_material/custom_material.mtl
assets/cases/06_rendering/custom_material/custom_material.mtl.meta

https://github.com/cocos-creator/2d-tasks/issues/1394

add custom material example

---

assets/resources/spineboy/spineboy.json
assets/resources/spineboy/spineboy.txt

关联pr：
jsb-adapter：https://github.com/cocos-creator-packages/jsb-adapter/pull/133
cocos2d-x-lite：https://github.com/cocos-creator/cocos2d-x-lite/pull/1738
bindings-generator：https://github.com/cocos-creator/bindings-generator/pull/32
engine: https://github.com/cocos-creator/engine/pull/4362

modify 'spineboy' atlas res to adapt new spine version

---

assets/scripts/Tips/TipsManager.js

jkw game not support subpackas for 2d-tasks/issues/1456

---

assets/cases/06_rendering/01_custom_ia/ColorRect.js
assets/cases/06_rendering/custom_material/custom_material.effect

fixed:
https://github.com/cocos-creator/2d-tasks/issues/1528
https://github.com/cocos-creator/2d-tasks/issues/1526

fixed issues

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

https://github.com/cocos-creator/2d-tasks/issues/1389

fixed that websocket connection closed

---

assets/cases/02_ui/05_scrollView/ScrollView.fire

fix issue：https://github.com/cocos-creator/2d-tasks/issues/1632
修复 example-case -> ScrollView 的 inertia 效果异常

fix ScrollView bug for 2d-tasks/issues/1632

---

assets/cases/07_capture_texture/capture_to_native.js
assets/cases/07_capture_texture/capture_to_web.js
assets/cases/07_capture_texture/capture_to_wechat.js
assets/cases/07_capture_texture/textureRenderUtils.js

Re: cocos-creator/2d-tasks#1610
* changes: make functions' names look better and fix failing to capture image when opening capture_to_web

V2.1.3 change function names and fix image capture problem

---

assets/scripts/Tips/TipsManager.js

ban alipay related case

---

assets/scripts/Tips/TipsManager.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1364
支持微信 videoPlayer 测试例

support videoplayer case

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

Re: cocos-creator/2d-tasks#1093
add callback for reconnection of socket.io in 05_scripts/11_network/NetworkCtrl

add callback for reconnection event

---

assets/cases/07_capture_texture/capture_to_wechat.js

* Now it will change label when run this example not in wechat game.

add warning about run capture_to_wechat not in wechat game

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

re:https://github.com/cocos-creator/2d-tasks/issues/1728 
* add open, error and closed message for webSocket event response
* add disconnect message for socketIO event response

add more messages for event response

---

assets/cases/02_ui/09_videoplayer/VideoPlayerCtrl.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1740
微信平台禁用 videoPlayer keep_Ratio 按钮

ban videoPlayer keepRatio

---

assets/scripts/Tips/TipsManager.js

ban editbox case on alipay

---

assets/cases/dragonbones/ReplaceSlotDisplay.js

issue: https://github.com/cocos-creator/2d-tasks/issues/1858
修复example-case DragonBones换肤位置不正确的问题

Fix DragonBones replace skin example offset incorrect

---

assets/cases/subpackage/Subpackages.fire

https://github.com/cocos-creator/2d-tasks/issues/1852
之前的 pr https://github.com/cocos-creator/example-cases/pull/765 升上来没有同步到 button 的 transition

update button transition in subpackage scene

---

assets/cases/05_scripting/11_network/downloader-native/DownloaderCtrl.js

now audio will stop playing for deleting audio file before new audio download task start
#re cocos-creator/2d-tasks#1727

let audio normally download when audio is playing

---

assets/cases/07_capture_texture/capture_to_native.fire
assets/cases/07_capture_texture/capture_to_native.js
assets/cases/07_capture_texture/textureRenderUtils.js

https://github.com/cocos-creator/2d-tasks/issues/1855

fixed capture native

---

assets/scripts/Tips/TipsManager.js

by adding isIphone judge sign.

Add ios access to Native_Call

---

assets/cases/02_ui/09_videoplayer/StayOnBottom.meta
assets/cases/02_ui/09_videoplayer/StayOnBottom/barrage-animClip.anim
assets/cases/02_ui/09_videoplayer/StayOnBottom/barrage-animClip.anim.meta
assets/cases/02_ui/09_videoplayer/StayOnBottom/barrage.prefab
assets/cases/02_ui/09_videoplayer/StayOnBottom/barrage.prefab.meta
assets/cases/02_ui/09_videoplayer/StayOnBottom/stayOnBottomCtrl.js
assets/cases/02_ui/09_videoplayer/StayOnBottom/stayOnBottomCtrl.js.meta
assets/cases/02_ui/09_videoplayer/videoPlayer-stayOnBottom.fire
assets/cases/02_ui/09_videoplayer/videoPlayer-stayOnBottom.fire.meta
assets/scripts/Tips/TipsManager.js

issue: https://github.com/cocos-creator/2d-tasks/issues/1870
添加 StayOnBottom 功能范例

add VideoPlayer StayOnBottom example

---

assets/TestList.fire
assets/cases/01_graphics/02_particle/AutoRemoveParticle.fire
assets/cases/01_graphics/02_particle/ToggleParticle.fire
assets/cases/01_graphics/02_particle/ToggleParticle/ParticleControl.js
assets/res/prefabs/Search Block.prefab
assets/res/textures/sheep/AutoAtlas.pac.meta

关联issues：https://github.com/cocos-creator/2d-tasks/issues/1919

02_particle scenes optimize

---

assets/cases/05_scripting/11_network/socket-io.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1990
changeLog:
- 修复支付宝 / 百度上获取不到 io 全局对象的问题

set io as global var in socket-io

---

assets/cases/01_graphics/01_sprite/FilledSprite/FilledSpriteControl.js

https://github.com/cocos-creator/2d-tasks/issues/1983

Reduce the speed of sprite Filled change

---

assets/cases/01_graphics/02_particle/AutoRemoveParticle.fire
assets/cases/01_graphics/02_particle/ToggleParticle/ParticleControl.js

https://github.com/cocos-creator/2d-tasks/issues/1919
原先对这个 issues 的修改是直接修改项目，经过讨论后选择修改引擎粒子系统，所以还原 #783 的pr修改。

fixed #783pr error commit

---

assets/cases/02_ui/09_videoplayer/VideoPlayerCtrl.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1826
changeLog:
- 修复华为机访问网络视频崩溃的问题，网络视频通过 https 访问

fix net video crash on Huawei

---

assets/main menu/Menu.js

revert load next scene code

---

assets/TestList.fire
assets/cases/dragonbones/DragonBones.fire
assets/cases/dragonbones/ReplaceSlotDisplay.fire
assets/cases/spine/SpineSkin.fire
settings/builder.json
settings/project.json

issue: https://github.com/cocos-creator/2d-tasks/issues/2139

improve menu and spine / dragon bones case

---

settings/project.json

update default physics module excluding

---

assets/cases/06_rendering/custom_material/custom_material.effect
assets/cases/06_rendering/custom_material/gray_effect_material.effect
assets/cases/06_rendering/custom_material/wate_effect_material.effect

re: https://github.com/cocos-creator/fireball/pull/9331

fixed effect error

---

assets/cases/05_scripting/10_network/socket-io.js

Re: https://github.com/cocos-creator/2d-tasks/issues/2221
changeLog:
- 修复小米平台上 userAgent 访问报错的问题
详细说明看这个 pr: https://github.com/cocos-creator/test-cases/pull/75

fix navigator on xiaomi for example-cases

---

assets/cases/07_capture_texture/capture_to_native.fire
assets/cases/07_capture_texture/capture_to_web.fire
assets/cases/07_capture_texture/capture_to_wechat.fire

https://github.com/cocos-creator/2d-tasks/issues/2144
修复截图背景色

refine capture camera clear color

---

assets/scripts/Tips/TipsManager.js

完善 videoPlayer-stayOnBottom 平台限制

improve videoPlayer-stayOnBottom platform restrictions

---

assets/cases/dragonbones/DragonBonesCollider.js
assets/cases/spine/SpineCollider.js

https://github.com/cocos-creator/2d-tasks/issues/2325#event-2927412136

fix skeleton collision debug draw flash

---

assets/cases/05_scripting/06_asset_loading/AssetLoading/AssetLoading.js
assets/cases/05_scripting/10_network/downloader-native.fire
assets/cases/05_scripting/10_network/downloader-native/DownloaderCtrl.js

修复几个 url 无法访问的问题
https://github.com/cocos-creator/2d-tasks/issues/2324
https://github.com/cocos-creator/2d-tasks/issues/2126

change some url to https

---

assets/cases/3d_physics/scripts/raytest.ts
assets/cases/3d_physics/scripts/trigger-testing.ts

https://github.com/cocos-creator/engine/pull/6079

v2.3.0 modify physics event name

---

assets/cases/dragonbones/DragonBonesAttach.fire
assets/cases/dragonbones/DragonBonesAttach.fire.meta
assets/cases/spine/SpineAttach.fire
assets/cases/spine/SpineAttach.fire.meta

spineAttach和dragonboneAttach 勾选自动释放资源

auto release assets

---

assets/scripts/Tips/TipsManager.js

Re: https://github.com/cocos-creator/2d-tasks/issues/2513
changeLog:
- 增加微信 pc 平台

add wechat pc

---

assets/cases/02_ui/16_safeArea.meta
assets/cases/02_ui/16_safeArea/SafeArea.fire
assets/cases/02_ui/16_safeArea/SafeArea.fire.meta
assets/scripts/Tips/TipsManager.js

https://github.com/cocos-creator/2d-tasks/issues/2503
添加 SafeArea 组件范例

add SafeArea example

---

assets/resources/test_assets/scene.fire
assets/resources/test_assets/scene.fire.meta

重新保存下 Preload Asset 中的预加载场景，之前的场景没有相机数据，加载之后无法正常显示。

Resave the preloaded test scene.

---

assets/cases/asset_bundle/TestBundle.meta
assets/resources.meta

https://github.com/cocos-creator/2d-tasks/issues/2879

adjust resources bundle

---

assets/cases/03_gameplay/01_player_control/OnMultiTouch/OnMultiTouchCtrl.js

Becase UC mobile browser element call requestFullScreen will lead to the game can't support mutiTouch.

add tips for multiTouch scene

---

assets/cases/03_gameplay/03_animation/CurveAnimation/CurveAnimation.js
assets/cases/03_gameplay/03_animation/CurveAnimation/CurveAnimation.js.meta
assets/i18n/data/en.js
assets/i18n/data/zh.js

Add an example case for curve animation.

---

assets/cases/05_scripting/07_module/Monster.js

（this.image.spriteFrame）this object is already be null;

case/05_scripting/07_module --Error report when switching scene
