cocos/example-projects

assets/cases/05_scripting/11_network/NetworkCtrl.js

https://github.com/cocos-creator/fireball/issues/4669
修复：用户切换到 NewWork 场景中在切回主界面以后关闭模拟器会出现 socketIO is null 的报错信息

fix Network err for fireball/issues/4669

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/VideoPlayerCtrl.js

忘了提交了。。。
https://github.com/cocos-creator/fireball/issues/4704
在 toggleFullscreen 中判断指定的机器，这些机器上有可能会出现崩溃的问题。
所以直接忽略 toggleFullscreen 操作。

Add log - video may be crash

---

assets/cases/03_gameplay/03_animation/SpriteAnimation/SheepAnimationCtrl.js
assets/cases/03_gameplay/03_animation/SpriteAnimation/SheepAnimationCtrl.js.meta

把 setTimeOut 修改为 scheduleOnce，解决快速切换界面导致播放动画时报 cocos-creator/fireball/issues/5464 的错误

fix cocos-creator/fireball/issues/5464

---

assets/cases/05_scripting/07_asset_loading/LoadRes/LoadRes_example.js

LoaRes 释放资源的时候需要传入类型，否则会导致释放失败，所以修改了一下范例用 getRes
@nantas  有空的时候合并一下

fix LoadRes_example bug, release asset error

---

assets/cases/dragonbones/DragonBonesCtrl.js

For https://github.com/cocos-creator/fireball/issues/6937
@jareguo 这里的问题是在切换场景时，DragonBones 的 onDisable 会去做 bullet 的 clean 操作，导致 bullet 直接 removeFromParent 移除。而 DragonBones 的 onDisable 调用是在下面的逻辑中发生的
https://github.com/cocos-creator/engine/blob/master/cocos2d/core/utils/base-node.js#L1024
由于 DragonBones 和 bullets 是在同一个父节点下，base-node 代码中的 children.length 发生了改变，循环开始时获取的 len 已经失效了，进而导致 node = children[i] 获取的是 undefined。
麻烦看下这里该如何优化逻辑，理论上来说任何在 onDisable 时操控同级节点（增删）的行为都会导致问题。

Fix DragonBones swtich scene issue

---

assets/scripts/Global/TipsManager.js

https://github.com/cocos-creator/fireball/issues/7303
调整一下，之前是隐藏 tips 的 sprite，但是在 tips 的节点上还有禁止触摸的事件，所以导致了，7303 的 bug 出现

fix fireball/issues/7303

---

assets/cases/05_scripting/11_network/socket-io.js

cocos-creator/engine#2674
add a new judgement that forbid the user to translate socket-io to es5 model

 forbid the user to translate socket-io to ES5 mode

---

assets/i18n/i18n.js

https://github.com/cocos-creator/fireball/issues/7767
需要调整一下 i18n 的 require 语言方式，应该传入字符串，不然会导致导出资源获取不到关联的脚本

update the require language in i18n

---

assets/cases/03_gameplay/02_actions/RotationAction.fire

https://github.com/cocos-creator/fireball/issues/8005
修复 example-03/02->RotationAction 按钮字母被截断

fix RotationAction label overflow type for fireball/issues/8005

---

assets/cases/anysdk/08_adtracking.fire

for issues, https://github.com/cocos-creator/fireball/issues/8027
PR, https://github.com/cocos-creator/example-cases/pull/469 重名了脚本文件名，但是忘记更改了场景中引用的脚本名

correct scriptName "AdTracking" mismatch

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/VideoPlayerCtrl.js
assets/cases/02_ui/09_videoplayer/videoPlayer.fire
assets/res/prefabs/AnySDKItem.prefab.meta
assets/res/prefabs/Background.prefab.meta
assets/res/prefabs/Monster.prefab.meta
assets/res/prefabs/Page.prefab.meta
assets/res/prefabs/SuspensionTips.prefab.meta
assets/res/prefabs/item0.prefab.meta
assets/res/prefabs/leftSprite.prefab.meta
assets/res/prefabs/loadAnimTest.prefab.meta
assets/res/prefabs/loadItem.prefab.meta
assets/res/prefabs/rightSprite.prefab.meta
settings/builder.json

Re: https://github.com/cocos-creator/example-cases/issues/553
修改场景内容：
1. 修改了资源远程本地的切换按钮
2. 增加了一个 SuspersionTips 用于提示，无法全屏播放。
微信开发者工具视频加载时间过长，没有显示，但无报错。
预览正常
模拟器不支持这个场景
手机构建 web 正常显示。
多提了一个 commit 内容是更新一下 1.10 example 里面的数据，不然每次用 1.10 打开都会有这些内容生成。
setting 将默认构建竖屏改成横屏。

modify the videoplayer fire

---

assets/cases/02_ui/08_editBox/EditBox/EditBoxEvent.js
assets/cases/02_ui/08_editBox/EditBox/EditBoxEvent.js.meta
assets/cases/02_ui/08_editBox/EditBoxEvent.fire
assets/cases/02_ui/08_editBox/EditBoxEvent.fire.meta

Re: https://github.com/cocos-creator/fireball/issues/8137
添加 editBox 事件绑定测试例，包括
- editingDidBegan
- editingDidEnded
- editingReturn
- textChanged
以及提供 stayOnTop 模式的测试

add editBox event handler case

---

assets/cases/07_render_texture/render_to_sprite.fire
assets/cases/07_render_texture/render_to_sprite.js
settings/creator-luacpp-support.json

增加一个 button，用以验证保存文件到本地
保存文件的主要测试代码：
```
let data = this.renderTexture.readPixels();
let width = this.renderTexture.width;
let height = this.renderTexture.height;
let filePath = jsb.fileUtils.getWritablePath() + 'render_to_sprite_cocos.png';
let success = jsb.savePixelsToFile(data, width, height, filePath);
if (success) {
cc.log("save  render texture success, file: " + filePath);
}
```
保存后的图片：
mac 平台：
android 平台：

test save render texture to file on native platform

---

assets/cases/02_ui/09_videoplayer/VideoPlayer/VideoPlayerCtrl.js
assets/cases/02_ui/09_videoplayer/videoPlayer.fire
assets/i18n/data/en.js
assets/i18n/data/zh.js

Re: https://github.com/cocos-creator/example-cases/issues/553
修改场景内容：
1.修改了资源远程本地的切换按钮
2. 增加了一条文本提示。
预览正常
模拟器不支持这个场景
手机构建 web 正常显示.
2. 存在问题： 由于使用了 2.0 的 TipsManager 创建提示信息， video 居中放置会导致文本显示被 videoPlay 给覆盖住，所以我将它下移了一部分距离，给 Tips 留下足够的空间用于显示信息。不是特别好看。

modify the video fire

---

assets/cases/02_ui/08_editBox/EditBox/EditBoxEvent.js
assets/cases/02_ui/08_editBox/EditBoxEvent.fire

Re: 
https://github.com/cocos-creator/fireball/issues/8348
https://github.com/cocos-creator/fireball/issues/8338
- 重新调整 editBoxEvent 布局，避免移动端测试 label 被键盘挡住
- 在不支持的平台禁用 stayOnTop 选项, 只有 web 平台支持 stayOnTop

update editBoxEvent scene

---

assets/cases/05_scripting/03_events/EventInMask.fire

Re: https://github.com/cocos-creator/fireball/issues/8389
按钮事件绑定了两次

fix eventInMask change node index

---

assets/cases/dragonbones/loadDragonBones/loadDragonBonesCtrl.js

Re: https://github.com/cocos-creator/2d-tasks/issues/458
1. 避免动态加载资源过程中用户切换场景导致报错。保姆式编程的罪过。。。。

fixed the dragonBone load error

---

assets/cases/07_render_texture/render_to_sprite.js

Re: https://github.com/cocos-creator/2d-tasks/issues/409
根据论坛反馈，截图一直是倒置的，所以针对这个问题做一下临时处理。因为问题本身属于 bug，但是目前没有好的方案修复，所以在 issue 处理完成之前，添加临时方案。

add a new function filpY  the capture

---

assets/TestList.fire
assets/cases/02_ui/16_safeArea.meta
assets/cases/02_ui/16_safeArea/IOS_SafeArea.fire
assets/cases/02_ui/16_safeArea/IOS_SafeArea.fire.meta
assets/cases/02_ui/16_safeArea/SafeArea.meta
assets/cases/02_ui/16_safeArea/SafeArea/SafeAreaCtrl.js
assets/cases/02_ui/16_safeArea/SafeArea/SafeAreaCtrl.js.meta
assets/scripts/Tips/TipsManager.js

Re: https://github.com/cocos-creator/example-cases/issues/582
只开放 ios 平台。
getSafeAreaRect 获取的是 view 像素大小，所以需要添加一层计算，将坐标定位为 canvas 坐标大小。

add a scene to get the ios safeArea

---

assets/cases/07_capture_texture/capture_to_native.fire
assets/cases/07_capture_texture/capture_to_native.fire.meta
assets/cases/07_capture_texture/capture_to_native.js
assets/cases/07_capture_texture/capture_to_web.fire
assets/cases/07_capture_texture/capture_to_web.js
assets/cases/07_capture_texture/capture_to_wechat.fire
assets/cases/07_capture_texture/capture_to_wechat.js
assets/cases/07_capture_texture/textureRenderUtils.js
assets/cases/07_capture_texture/textureRenderUtils.js.meta

Re: https://github.com/cocos-creator/2d-tasks/issues/719
Re: https://github.com/cocos-creator/2d-tasks/issues/730
Re: https://github.com/cocos-creator/2d-tasks/issues/737
1. 整理现有的三个截图场景，让每个场景都具有展示 sprite 的功能，并且具有保存正确方向截图的能力。
2. 提取了部分可公用代码，试每个场景脚本内容更新家清晰。
render_to_sprite 已被清除，更换为 capture_to_native

sort the capture scene scripts

---

assets/cases/07_capture_texture/capture_to_web.js

Re: https://github.com/cocos-creator/2d-tasks/issues/739
大部分的手机浏览器不支持 直接下载 base64 格式图片，因此找个办法转码成 blob 格式通过生成新的 URL 链接进行下载。
修复移动端浏览器下载 capture image 失败问题

fixed the mobile download the capture image failed problem

---

assets/cases/05_scripting/07_asset_loading/LoadResDir/loadResDir_example.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1092
05_scripting/07_asset_loading->LoadResDir 测试例中，
加载所有资源的过程中，将已经加载的 spriteFrame 释放，会造成部分 png 被 texutre 引用无法释放

fix clear assets when loadResDir

---

assets/cases/02_ui/05_scrollView/ListView/Item.js
assets/cases/02_ui/05_scrollView/ListView/ListViewCtrl.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1162
修复 listView tmplID 的问题
tmplID 应该初始化之后就不再改变了，而 itemID 应该随着视图的滚动动态更新

fix tmplID in listView case

---

assets/cases/05_scripting/11_network/downloader-native/DownloaderCtrl.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1157
修复 downloader-native 同一对象多个下载进程冲突问题
做了点击防护处理，当前有对象正在下载过程中不进行新的对象下载进程

fixed the problem that downloading in the native target repeat  error

---

assets/cases/02_ui/08_editBox/EditBox.fire
assets/cases/02_ui/08_editBox/EditBox.fire.meta
assets/cases/02_ui/08_editBox/EditBox/EditBoxEvent.js
assets/cases/02_ui/08_editBox/EditBox/EditBoxFocus.js
assets/cases/02_ui/08_editBox/EditBoxEvent.fire
assets/cases/02_ui/08_editBox/EditBoxEvent.fire.meta
assets/cases/02_ui/08_editBox/EditBoxTabIndex.fire
assets/cases/02_ui/08_editBox/EditBoxTabIndex.fire.meta

更新 2.1 editBox 相关测试例
调整多行输入 不正确的 placeholderLabel 行高
tabIndex 测试例，调整 editBox 高度，方便测试编辑状态下切换 editBox 可能造成的问题
editBoxEvent 测试例去掉 stayOnTop 选项

update 2.1 editBox cases

---

assets/cases/3d/mesh-texture.effect.meta
assets/main menu/Menu.js
assets/res/3d/mixamo/model.fbx.meta
assets/res/3d/mixamo/model@Capoeira.fbx.meta
assets/res/3d/mixamo/model@Defeated.fbx.meta

https://github.com/cocos-creator/2d-tasks/issues/1272
移除 Menu.js 中的监听 back 事件，之前是为什么方便快速返回到主菜单，但是这样会影响到 videoplayer 范例，所以进行移除

 fix cocos-creator/2d-tasks/issues/1272

---

assets/cases/05_scripting/11_network/socket-io.js.meta
assets/resources/materials.meta

https://github.com/cocos-creator/2d-tasks/issues/1336
由于没有勾选运行 Native 平台加载导致 socket-io 加载失败

fix socket-io bug for cocos-creator/2d-tasks/issues/1336

---

assets/i18n/LabelLocalized.js

关联 pr: https://github.com/cocos-creator/engine/pull/5330
LabelLocalized 组件继承自 CCLabel 组件
应该调用父类的 onLoad

call label default onload on example-case

---

assets/cases/05_scripting/11_network/socket-io.js

Re: https://github.com/cocos-creator/2d-tasks/issues/1841
changeLog:
- 修复 v2.2 上 socket-io 插件的报错
v2.2 移除了 CC_WECHATGAME 宏，CC_WECHATGAME 变成了全局变量，小米平台需要显式访问 window 的属性

fix socket-io plugin on xiaomi platform

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

re:cocos-creator/2d-tasks#1728
add "Opened", "Error" and "Close" states to websocket state info
add some xhr events states as well

Add more messages for websocket and xhr events states displaying

---

assets/cases/collider/Platform/HeroControl.js

Change jump logic.
re:https://forum.cocos.com/t/update-this-node-y-this-speed-y-dt/59036/3

fix wrong jump height in case platform

---

assets/cases/05_scripting/11_network/NetworkCtrl.js

https://github.com/cocos-creator/2d-tasks/issues/1989
changeLog:
- 修复 Android 平台，加了 md5Cache 后，websocket 请求失败的问题
nativeUrl 是没有加 md5 的路径，导致证书路径不正确

fix md5 url for wssCacert

---

assets/cases/05_scripting/10_loadingBar/LoadingBarCtrl.js

https://github.com/cocos-creator/2d-tasks/issues/2098
changeLog:
- 修复 loadingBar 场景资源加载路径错误的问题

fix resource loading

---

assets/cases/07_capture_texture/textureRenderUtils.js

cc.visibleRect在部分设备返回值为1.00000000001
导致后续计算 data[start + i]=undefined，进而导致截图异常

修复部分情况下截图是全白透明的bug
